// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRW_yewx0ULWzoqZrgUxP94L8OGVvqQGQ',
    appId: '1:1041245264815:web:c2e4efe31a62af0f4cad5a',
    messagingSenderId: '1041245264815',
    projectId: 'todolistapp-930a9',
    authDomain: 'todolistapp-930a9.firebaseapp.com',
    storageBucket: 'todolistapp-930a9.appspot.com',
    measurementId: 'G-JSF8VBCZ7V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAel6SGJmQAx1UuyvLgn631kMg-PGs3zzo',
    appId: '1:1041245264815:android:c6e574519583fd184cad5a',
    messagingSenderId: '1041245264815',
    projectId: 'todolistapp-930a9',
    storageBucket: 'todolistapp-930a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA97jOX4mfbnzQl22M8MXpBI2lzw4x1D6I',
    appId: '1:1041245264815:ios:1057b9d98c693bfc4cad5a',
    messagingSenderId: '1041245264815',
    projectId: 'todolistapp-930a9',
    storageBucket: 'todolistapp-930a9.appspot.com',
    androidClientId: '1041245264815-1jpih1nfddvje6eqeqvdhi0s0vr34t4i.apps.googleusercontent.com',
    iosClientId: '1041245264815-511d64dndc1qqde81ovelqam495qg9sk.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTodolistGooglemaps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA97jOX4mfbnzQl22M8MXpBI2lzw4x1D6I',
    appId: '1:1041245264815:ios:66fea221189723f84cad5a',
    messagingSenderId: '1041245264815',
    projectId: 'todolistapp-930a9',
    storageBucket: 'todolistapp-930a9.appspot.com',
    androidClientId: '1041245264815-1jpih1nfddvje6eqeqvdhi0s0vr34t4i.apps.googleusercontent.com',
    iosClientId: '1041245264815-000tk5hhc5j6k75irtbnp8ko28e93mbu.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTodolistGooglemaps.RunnerTests',
  );
}
